Traceback (most recent call last):
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/df/anaconda3/envs/ml/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@njit(parallel = True, fastmath = True)
def p5 (n : int) -> np.ndarray:
  """Sieve of Eratosthenes"""
  primes = np.full(shape = n, fill_value = True)
  primes[0], primes[1] = False, False # 0 and 1 are not prime
  for i in prange(2, int(n ** 0.5) + 1, 2):
    if primes[i]:
      primes[i*i::i] = False
  return np.flatnonzero(a = primes)

%timeit p5(int(1e7))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[18], line 1[0m
[0;32m----> 1[0m [38;5;129m@njit[39m(parallel [38;5;241m=[39m [38;5;28;01mTrue[39;00m, fastmath [38;5;241m=[39m [38;5;28;01mTrue[39;00m)
[1;32m      2[0m [38;5;28;01mdef[39;00m [38;5;21mp5[39m (n : [38;5;28mint[39m) [38;5;241m-[39m[38;5;241m>[39m np[38;5;241m.[39mndarray:
[1;32m      3[0m [38;5;250m  [39m[38;5;124;03m"""Sieve of Eratosthenes"""[39;00m
[1;32m      4[0m   primes [38;5;241m=[39m np[38;5;241m.[39mfull(shape [38;5;241m=[39m n, fill_value [38;5;241m=[39m [38;5;28;01mTrue[39;00m)

[0;31mNameError[0m: name 'njit' is not defined

